### ISSUE TITLE
Nice repo, Can you update the readme? 

### ISSUE THREAD

**Issue by aertist** [eps696/stylegan2ada#1]
All the relative paths are confusing.

**Comment by eps696** [comment]
tell a bit more, how would you like to see it?
do you mean the placement of source data, or what?

[please note, that i've mostly followed file structure, inherited from the original stylegans, assuming it's well known already; it's quite out of scope to double their guidelines here]

**Comment by eps696** [comment]
ok, i added some generic file tree illustration (with the same names as in examples). 
let me know if it helps.

**Comment by aertist** [comment]
Sorry for the vague description. 
I got confused between where to place the `.zip` dataset file. Also this repo doesn't convert the dataset into `.tfrecords` format before processing? (I'm a newbie in ML space)

I tried the [`model tweaking`](https://colab.research.google.com/github/eps696/stylegan2/blob/master/StyleGAN2_colab.ipynb#scrollTo=aiItkMSM8APO) function in `StyleGAN2` colab notebook but it shows errors. (Model is trained with `StyleGAN2-ADA`)
It also shows error when I try to use the [`Multi-latent generation`](https://colab.research.google.com/github/eps696/stylegan2/blob/master/StyleGAN2_colab.ipynb#scrollTo=cOGVIJt18APL) function in both of the colab notebooks.

At last I figured out where to place the `.zip` dataset file and [`Native and Custom size generations`](https://colab.research.google.com/drive/1DlOGL4O9vEAq3C-y2EQ6ogVUadypkB4D?authuser=2#scrollTo=GwoOBOcR8APK) cells worked for me on colab. Example video I made from it. [link](https://youtu.be/09ZcYK_ozQQ)

I was trying to implement this with a new project, which syncs the latent interpolation video with music. The tool is called [Lucid Sonic Dreams](https://github.com/mikaelalafriz/lucid-sonic-dreams). An example video I made from this can be found [here](https://youtu.be/2xEGK1iuLGE).

The problem with this tool is, it uses the original `StyleGAN2-ADA` repo and only allows the generation of square videos (as you can see in the linked video above)

Can you implement this in your repo? It will make a good tool for artists like me and others :)

**Comment by eps696** [comment]
1) all datasets are in `data` directory. tfrecords were used in old tf version; this one is on pytorch and takes data directly from image folders or archives.
2) as stated in readme, stylegan2-ada  can load models from old stylegan2, but not vice versa. glad to hear that you sorted out colab usage. 
3) didn't quite catch, what do you offer me to implement?

**Comment by aertist** [comment]
I was trying to generate a 1920x1080 audio reactive latent space interpolation video from this repo and the tool I mentioned above ([Lucis-Sonic-Dreams](https://github.com/mikaelalafriz/lucid-sonic-dreams)). But couldn't figure out the way to implement this. 
I am relatively new in ML and Computer Vision. 😅
Maybe you can help?

Also, can you tell me more about this `gen.bat ffhq-1024 1024-1024 100-20 --latmask _in/mask.jpg` command. How to use this and how does it work and why it is different from the normal generations?

Thanks 👀

**Comment by eps696** [comment]
1. unfortunately life is short, and i don't fancy pulling every foreign feature into my code. you may ask the author[s] of that repository, if they are interested in implementing custom size generation instead. or just learn and make such progress yourself; after all, it's not a rocket science. 
2. to use the command - just type and run it from the repo root directory. to see how it works - just look at the results in the output directory, it's pretty self-explanatory. you may want to take some classes, or read materials "on the internet" about styleGAN, other GANs or ML in general; since efficient work with ML tools does requires some tech understanding. alas, i doubt i can invest more time in explaining such basics. 
3. since the original request is resolved, i'm closing the issue. feel free to contact me on other soc.media platforms (same nickname) if you have other generic questions (taking into account what's said above).

**Comment by eps696** [comment]
@aertist here is a [patreon](https://www.patreon.com/eps696) acc for some details and internals of my process. you may consider joining it, if you feel appropriate (please don't overlook the importance of basic self-education anyway)
