### ISSUE TITLE
Change aspect ratio of a trained model

### ISSUE THREAD

**Issue by smithee771** [eps696/stylegan2ada#15]
Hi @eps696 first of all many thanks for your code.
I'm using your colab notebook to try to change aspect ratio of a model. After trying some models without success I found in another issue a model that it was supposed to work: 
Issue "Arbitrary resolution for torch models #2"
Model https://drive.google.com/file/d/1OHuKMJFH0b85ql2vMrD9bWYFjAiwvXAE/view

But also using this model I'm getting this error:
AssertionError:  !! G/D subnets not found in source model !!

Is it a only colab issue? Any hint?
Many thanks

**Comment by eps696** [comment]
that message means two things:
1) you're trying to change not just aspect, but the core resolution of the model, by adding or removing the layers [i.e. your output res is too different from the base one]. since this operation effectively adds untrained weights, it's supposed to be applied only to full [G/D/Gs] models [for further finetuning].
2) your model contains only Gs subnet for generation, missing D/G subnets [required for finetuning]. therefore the conversion is stopped.

**Comment by eps696** [comment]
[closed for inactivity]
