### ISSUE TITLE
Drive keep unmounting

### ISSUE THREAD

**Issue by flaclad** [eps696/stylegan2ada#3]
I'm experiencing a weird behavior with the drive folder keeping unmounting. After running the general setup cell and successfully downloading files in sg2a_eps I get

ERROR:root:File `'src/train.py'` not found.
[Errno 107] Transport endpoint is not connected: '/G/MyDrive/sg2a_eps/'
/G/MyDrive/sg2a_eps

Installing collected packages: ninja
Successfully installed ninja-1.10.0.post2
Mounted at /G
/G/MyDrive
/G/MyDrive/sg2a_eps
Requirement already satisfied: click in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 1)) (7.1.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 2)) (5.4.8)
.. Done ..

**Comment by eps696** [comment]
thanks for reporting. unfortunately, i wasn't able to reproduce this. could you give more info, how exactly did you get it? 
- the order of actions before that (starting from scratch, reconnecting, restarting session, etc.)
- the status of G drive before that (if the directory existed, if credentials are copied properly, etc.)
- the status after that 'General setup' cell (if the drive is connected, directories copied, etc.)
- some other relevant info (browser, any drive-related extenstions, etc.)

since this seems to be the problem between colab and drive (not directly related to the notebook operations, which i have control of), you may also want to google such errors on colab forums, [like this](https://github.com/googlecolab/colabtools/issues/284).

**Comment by eps696** [comment]
i managed to face the errors like `Transport endpoint is not connected` in case the G-drive icon (in the Files section on the left menu of Colab) is pressed after General setup is completed, and G-drive is already connected. On that action, Colab inserts a cell with code to create new connection to drive, effectively losing the original one. 
So general advice to avoid that - do not touch that icon (or at least do not run that extra auto-added cell). 

The issue may be reopened, if the problem persists even in such conditions, and if there are more details (see questions above).
