### ISSUE TITLE
ModuleAttributeError: 'Generator' object has no attribute 'init_res'

### ISSUE THREAD

**Issue by moiseshorta** [eps696/stylegan2ada#8]
Hey Vadim,

I seem to be having this error whenever I try to generate using custom size, multi-latent generation or 'other tricks' digression mode.

Native generation seems to be working just fine, but I'm really missing these features as compared to the original SG2.

I'm trying to generate from a SG2-ada-pytorch .pkl.

Thanks for your work on maintaining this repo!

**Comment by eps696** [comment]
thanks for bringing my attention to it. this is open problem in fact. 

if the model is not made with one of my repos, it may need to be reconstructed to allow such extended use (so that required attributes are inserted into the model). this procedure is available at tweaking models section in [another repo](https://github.com/eps696/stylegan2): 
`model_convert.bat SG2-ada-pytorch.pkl -r` (or similar section in [colab](https://colab.research.google.com/github/eps696/stylegan2/blob/master/StyleGAN2_colab.ipynb))

unfortunately, this works only for "standard" sg2 models, following original nvidia pkl format from TF-based repos; i haven't dealt with (new) pytorch models conversion/reconstruction yet. one possible workaround might be to try finetuning such model with this repo, but stopping at the first (zero) iteration - then the model would be reconstructed but the weights not changed yet. the latter is just my quick guess, let me know if that works for you. 

if you provide me an example of such model, i may give more thorough look on the whole procedure.

**Comment by eps696** [comment]
i am closing the issue for inactivity, guessing that the question is answered (feel free to reopen, if not).
